"""Az'arch calamares source patch -- add the "Network" installer page (networkq QML module).

The FOURTH Az'arch source patch applied to the pinned calamares-3.4.2 tarball in the
recipe's prepare() (see pkgbuild_calamares). Kept in its own module so each patch is a
focused, independently-editable unit; pkgbuild_calamares re-exports the name-constant and
builder below, and pkgbuild.py re-exports them in turn, so callers and recipe_dirs() use
them unchanged.

Unlike the other three patches (which EDIT existing files), this one CREATES a whole new
QML view module under src/modules/networkq/ via `--- /dev/null` / `+++ b/...` hunks. No
top-level CMake edit is needed: src/modules/CMakeLists.txt GLOBS its subdirectories and
calls calamares_add_module_subdirectory() on each, so a new networkq/ directory is picked
up automatically. QML is enabled in the Az'arch build (WITH_QML=ON); the module's
CMakeLists guards on WITH_QML and skips cleanly if it were ever off.

WHAT THE PAGE DOES. A "Network" page with an "Automatic (DHCP)" (default) vs "Manual"
radio; when Manual, five text fields -- IPv4 address, subnet mask, default gateway,
DNS 1, DNS 2 -- two-way bound to a C++ Config QObject. On page-leave the view step's
onLeave() calls Config::finalizeGlobalStorage(), which publishes the choice to
GlobalStorage: "networkMethod" always, and (only for manual) "networkIpv4",
"networkSubnetMask", "networkGateway", "networkDns1", "networkDns2". The companion
networkcfg-static patch (a separate module) reads those keys at exec time and writes a
0600 static NetworkManager profile on the installed target. DHCP leaves stock behaviour.

The diff is assembled from a line-by-line list of strings so every unified-diff CONTEXT
line keeps its exact single leading space -- a triple-quoted literal would let an editor
strip trailing spaces and silently break `patch`. A context drift on a version bump makes
`patch` fail LOUDLY in prepare() (the build aborts) rather than silently dropping the
feature; regenerate the hunks via `diff -u /dev/null <file>` against the new source then.
"""

from __future__ import annotations


CALAMARES_NETWORKQ_PATCH_NAME = "azarch-calamares-networkq.patch"


def calamares_networkq_patch() -> str:
    r"""Unified diff (-p1) applied to the extracted calamares-3.4.2 source in the
    recipe's prepare(): CREATE the src/modules/networkq/ QML view module (Config,
    NetworkQmlViewStep, networkq.qml, networkq.qrc, networkq.conf, CMakeLists.txt) that
    adds the "Network" installer page. Each file is a `--- /dev/null` new-file hunk, so
    the patch only ever ADDS files; the module is auto-discovered by the src/modules
    CMake glob. Verified to apply with `patch -p1 --fuzz=0` against the pinned tarball.

    Same authoring rule as the sibling patches: assembled line-by-line so every
    unified-diff line (context, addition, blank context) keeps its exact leading
    character. Regenerate via `diff -u /dev/null <file>` on a version bump.
    """
    lines = [
        "--- /dev/null",
        "+++ b/src/modules/networkq/Config.h",
        "@@ -0,0 +1,79 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Az'arch: network configuration page (static IPv4 vs DHCP). See networkq.qml.",
        "+ */",
        "+",
        "+#ifndef NETWORKQ_CONFIG_H",
        "+#define NETWORKQ_CONFIG_H",
        "+",
        "+#include \"DllMacro.h\"",
        "+",
        "+#include <QObject>",
        "+#include <QString>",
        "+#include <QVariantMap>",
        "+",
        "+/**",
        "+ * Backing object for the Az'arch \"Network\" QML page. Holds the DHCP/manual choice",
        "+ * and, for manual, the five static-IPv4 fields, and publishes them to GlobalStorage",
        "+ * on page-leave so the networkcfg job can write a static NetworkManager profile on",
        "+ * the target. Each field is a two-way QML property (READ/WRITE/NOTIFY).",
        "+ */",
        "+class PLUGINDLLEXPORT Config : public QObject",
        "+{",
        "+    Q_OBJECT",
        "+",
        "+    // \"dhcp\" (default) or \"manual\". Only when \"manual\" are the five fields written.",
        "+    Q_PROPERTY( QString method READ method WRITE setMethod NOTIFY methodChanged FINAL )",
        "+    Q_PROPERTY( QString ipv4 READ ipv4 WRITE setIpv4 NOTIFY ipv4Changed FINAL )",
        "+    Q_PROPERTY( QString subnetMask READ subnetMask WRITE setSubnetMask NOTIFY subnetMaskChanged FINAL )",
        "+    Q_PROPERTY( QString gateway READ gateway WRITE setGateway NOTIFY gatewayChanged FINAL )",
        "+    Q_PROPERTY( QString dns1 READ dns1 WRITE setDns1 NOTIFY dns1Changed FINAL )",
        "+    Q_PROPERTY( QString dns2 READ dns2 WRITE setDns2 NOTIFY dns2Changed FINAL )",
        "+",
        "+public:",
        "+    explicit Config( QObject* parent = nullptr );",
        "+    ~Config() override = default;",
        "+",
        "+    QString method() const { return m_method; }",
        "+    void setMethod( const QString& v );",
        "+",
        "+    QString ipv4() const { return m_ipv4; }",
        "+    void setIpv4( const QString& v );",
        "+",
        "+    QString subnetMask() const { return m_subnetMask; }",
        "+    void setSubnetMask( const QString& v );",
        "+",
        "+    QString gateway() const { return m_gateway; }",
        "+    void setGateway( const QString& v );",
        "+",
        "+    QString dns1() const { return m_dns1; }",
        "+    void setDns1( const QString& v );",
        "+",
        "+    QString dns2() const { return m_dns2; }",
        "+    void setDns2( const QString& v );",
        "+",
        "+    void setConfigurationMap( const QVariantMap& configurationMap );",
        "+",
        "+    /// Publish the current choice to GlobalStorage (called from the view step's onLeave()).",
        "+    void finalizeGlobalStorage() const;",
        "+",
        "+signals:",
        "+    void methodChanged( const QString& );",
        "+    void ipv4Changed( const QString& );",
        "+    void subnetMaskChanged( const QString& );",
        "+    void gatewayChanged( const QString& );",
        "+    void dns1Changed( const QString& );",
        "+    void dns2Changed( const QString& );",
        "+",
        "+private:",
        "+    QString m_method = QStringLiteral( \"dhcp\" );",
        "+    QString m_ipv4;",
        "+    QString m_subnetMask;",
        "+    QString m_gateway;",
        "+    QString m_dns1;",
        "+    QString m_dns2;",
        "+};",
        "+",
        "+#endif  // NETWORKQ_CONFIG_H",
        "--- /dev/null",
        "+++ b/src/modules/networkq/Config.cpp",
        "@@ -0,0 +1,107 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Az'arch: network configuration page backing object.",
        "+ */",
        "+",
        "+#include \"Config.h\"",
        "+",
        "+#include \"GlobalStorage.h\"",
        "+#include \"JobQueue.h\"",
        "+",
        "+Config::Config( QObject* parent )",
        "+    : QObject( parent )",
        "+{",
        "+}",
        "+",
        "+void",
        "+Config::setMethod( const QString& v )",
        "+{",
        "+    if ( v != m_method )",
        "+    {",
        "+        m_method = v;",
        "+        emit methodChanged( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setIpv4( const QString& v )",
        "+{",
        "+    if ( v != m_ipv4 )",
        "+    {",
        "+        m_ipv4 = v;",
        "+        emit ipv4Changed( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setSubnetMask( const QString& v )",
        "+{",
        "+    if ( v != m_subnetMask )",
        "+    {",
        "+        m_subnetMask = v;",
        "+        emit subnetMaskChanged( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setGateway( const QString& v )",
        "+{",
        "+    if ( v != m_gateway )",
        "+    {",
        "+        m_gateway = v;",
        "+        emit gatewayChanged( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setDns1( const QString& v )",
        "+{",
        "+    if ( v != m_dns1 )",
        "+    {",
        "+        m_dns1 = v;",
        "+        emit dns1Changed( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setDns2( const QString& v )",
        "+{",
        "+    if ( v != m_dns2 )",
        "+    {",
        "+        m_dns2 = v;",
        "+        emit dns2Changed( v );",
        "+    }",
        "+}",
        "+",
        "+void",
        "+Config::setConfigurationMap( const QVariantMap& configurationMap )",
        "+{",
        "+    // No module-level configuration keys are consumed; the page ships no defaults",
        "+    // beyond method=\"dhcp\". Kept for symmetry with the other view-step configs.",
        "+    Q_UNUSED( configurationMap )",
        "+}",
        "+",
        "+void",
        "+Config::finalizeGlobalStorage() const",
        "+{",
        "+    Calamares::GlobalStorage* gs = Calamares::JobQueue::instance()->globalStorage();",
        "+    if ( !gs )",
        "+    {",
        "+        return;",
        "+    }",
        "+",
        "+    // Always publish the method so the networkcfg job knows whether to act. The five",
        "+    // static fields are only meaningful (and only published) for a manual configuration;",
        "+    // an empty IPv4 is treated by the job as \"leave it on DHCP\".",
        "+    gs->insert( QStringLiteral( \"networkMethod\" ), m_method );",
        "+    if ( m_method == QStringLiteral( \"manual\" ) )",
        "+    {",
        "+        gs->insert( QStringLiteral( \"networkIpv4\" ), m_ipv4.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkSubnetMask\" ), m_subnetMask.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkGateway\" ), m_gateway.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkDns1\" ), m_dns1.trimmed() );",
        "+        gs->insert( QStringLiteral( \"networkDns2\" ), m_dns2.trimmed() );",
        "+    }",
        "+}",
        "--- /dev/null",
        "+++ b/src/modules/networkq/NetworkQmlViewStep.h",
        "@@ -0,0 +1,41 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Az'arch: \"Network\" QML view step (DHCP vs static IPv4). See Config.h / networkq.qml.",
        "+ */",
        "+",
        "+#ifndef NETWORKQMLVIEWSTEP_H",
        "+#define NETWORKQMLVIEWSTEP_H",
        "+",
        "+#include \"Config.h\"",
        "+",
        "+#include \"DllMacro.h\"",
        "+#include \"utils/PluginFactory.h\"",
        "+#include \"viewpages/QmlViewStep.h\"",
        "+",
        "+#include <QObject>",
        "+",
        "+class PLUGINDLLEXPORT NetworkQmlViewStep : public Calamares::QmlViewStep",
        "+{",
        "+    Q_OBJECT",
        "+",
        "+public:",
        "+    explicit NetworkQmlViewStep( QObject* parent = nullptr );",
        "+    ~NetworkQmlViewStep() override;",
        "+",
        "+    QString prettyName() const override;",
        "+",
        "+    void onLeave() override;",
        "+",
        "+    void setConfigurationMap( const QVariantMap& configurationMap ) override;",
        "+",
        "+    QObject* getConfig() override { return m_config; }",
        "+",
        "+private:",
        "+    Config* m_config;",
        "+};",
        "+",
        "+CALAMARES_PLUGIN_FACTORY_DECLARATION( NetworkQmlViewStepFactory )",
        "+",
        "+#endif  // NETWORKQMLVIEWSTEP_H",
        "--- /dev/null",
        "+++ b/src/modules/networkq/NetworkQmlViewStep.cpp",
        "@@ -0,0 +1,43 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Az'arch: \"Network\" QML view step.",
        "+ */",
        "+",
        "+#include \"NetworkQmlViewStep.h\"",
        "+",
        "+#include \"Config.h\"",
        "+",
        "+#include <QVariant>",
        "+",
        "+NetworkQmlViewStep::NetworkQmlViewStep( QObject* parent )",
        "+    : Calamares::QmlViewStep( parent )",
        "+    , m_config( new Config( this ) )",
        "+{",
        "+}",
        "+",
        "+NetworkQmlViewStep::~NetworkQmlViewStep() {}",
        "+",
        "+QString",
        "+NetworkQmlViewStep::prettyName() const",
        "+{",
        "+    return tr( \"Network\" );",
        "+}",
        "+",
        "+void",
        "+NetworkQmlViewStep::onLeave()",
        "+{",
        "+    // Push the DHCP/manual choice (and, when manual, the static fields) into",
        "+    // GlobalStorage so the networkcfg job can write a static profile on the target.",
        "+    m_config->finalizeGlobalStorage();",
        "+}",
        "+",
        "+void",
        "+NetworkQmlViewStep::setConfigurationMap( const QVariantMap& configurationMap )",
        "+{",
        "+    m_config->setConfigurationMap( configurationMap );",
        "+    Calamares::QmlViewStep::setConfigurationMap( configurationMap );  // call parent implementation last",
        "+}",
        "+",
        "+CALAMARES_PLUGIN_FACTORY_DEFINITION( NetworkQmlViewStepFactory, registerPlugin< NetworkQmlViewStep >(); )",
        "--- /dev/null",
        "+++ b/src/modules/networkq/networkq.qml",
        "@@ -0,0 +1,112 @@",
        "+/* === This file is part of Calamares - <https://calamares.io> ===",
        "+ *",
        "+ *   SPDX-License-Identifier: GPL-3.0-or-later",
        "+ *",
        "+ *   Az'arch \"Network\" page: choose Automatic (DHCP) or Manual static IPv4.",
        "+ *   The five manual fields are two-way bound to the C++ Config object exposed",
        "+ *   as `config`; Config.finalizeGlobalStorage() (view step onLeave) hands them",
        "+ *   to the networkcfg job, which writes a static NetworkManager profile on the",
        "+ *   installed target. `config` is the context property set by NetworkQmlViewStep.",
        "+ */",
        "+",
        "+import io.calamares.ui 1.0",
        "+",
        "+import QtQuick",
        "+import QtQuick.Controls",
        "+import QtQuick.Layouts",
        "+",
        "+Item {",
        "+    id: networkPage",
        "+    width: 800",
        "+    height: 520",
        "+",
        "+    // Convenience: the manual fields are only enabled when Manual is selected.",
        "+    property bool manual: config.method === \"manual\"",
        "+",
        "+    ColumnLayout {",
        "+        anchors.fill: parent",
        "+        anchors.margins: 24",
        "+        spacing: 18",
        "+",
        "+        Text {",
        "+            text: qsTr(\"Network\")",
        "+            font.pointSize: 18",
        "+            font.bold: true",
        "+        }",
        "+",
        "+        Text {",
        "+            Layout.fillWidth: true",
        "+            wrapMode: Text.WordWrap",
        "+            text: qsTr(\"Choose how this computer gets its network address. Automatic (DHCP) \" +",
        "+                       \"asks the network for one; Manual lets you enter a fixed IPv4 address.\")",
        "+        }",
        "+",
        "+        ColumnLayout {",
        "+            spacing: 6",
        "+",
        "+            RadioButton {",
        "+                id: dhcpRadio",
        "+                text: qsTr(\"Automatic (DHCP)\")",
        "+                checked: config.method === \"dhcp\"",
        "+                onClicked: config.setMethod(\"dhcp\")",
        "+            }",
        "+            RadioButton {",
        "+                id: manualRadio",
        "+                text: qsTr(\"Manual\")",
        "+                checked: config.method === \"manual\"",
        "+                onClicked: config.setMethod(\"manual\")",
        "+            }",
        "+        }",
        "+",
        "+        GridLayout {",
        "+            Layout.fillWidth: true",
        "+            columns: 2",
        "+            columnSpacing: 16",
        "+            rowSpacing: 10",
        "+            enabled: networkPage.manual",
        "+            opacity: networkPage.manual ? 1.0 : 0.5",
        "+",
        "+            Label { text: qsTr(\"IPv4 address\") }",
        "+            TextField {",
        "+                Layout.fillWidth: true",
        "+                placeholderText: \"192.168.1.50\"",
        "+                text: config.ipv4",
        "+                onTextEdited: config.setIpv4(text)",
        "+            }",
        "+",
        "+            Label { text: qsTr(\"Subnet mask\") }",
        "+            TextField {",
        "+                Layout.fillWidth: true",
        "+                placeholderText: \"255.255.255.0\"",
        "+                text: config.subnetMask",
        "+                onTextEdited: config.setSubnetMask(text)",
        "+            }",
        "+",
        "+            Label { text: qsTr(\"Default gateway\") }",
        "+            TextField {",
        "+                Layout.fillWidth: true",
        "+                placeholderText: \"192.168.1.1\"",
        "+                text: config.gateway",
        "+                onTextEdited: config.setGateway(text)",
        "+            }",
        "+",
        "+            Label { text: qsTr(\"DNS 1\") }",
        "+            TextField {",
        "+                Layout.fillWidth: true",
        "+                placeholderText: \"1.1.1.1\"",
        "+                text: config.dns1",
        "+                onTextEdited: config.setDns1(text)",
        "+            }",
        "+",
        "+            Label { text: qsTr(\"DNS 2\") }",
        "+            TextField {",
        "+                Layout.fillWidth: true",
        "+                placeholderText: \"8.8.8.8\"",
        "+                text: config.dns2",
        "+                onTextEdited: config.setDns2(text)",
        "+            }",
        "+        }",
        "+",
        "+        Item { Layout.fillHeight: true }",
        "+    }",
        "+}",
        "--- /dev/null",
        "+++ b/src/modules/networkq/networkq.qrc",
        "@@ -0,0 +1,5 @@",
        "+<!DOCTYPE RCC><RCC version=\"1.0\">",
        "+<qresource>",
        "+  <file alias=\"networkq.qml\">networkq.qml</file>",
        "+</qresource>",
        "+</RCC>",
        "--- /dev/null",
        "+++ b/src/modules/networkq/networkq.conf",
        "@@ -0,0 +1,15 @@",
        "+# SPDX-License-Identifier: CC0-1.0",
        "+#",
        "+# Az'arch \"Network\" QML page (Automatic/DHCP vs Manual static IPv4). The page has no",
        "+# tunable behaviour of its own; the only configurable thing is the sidebar/progress",
        "+# label, kept here so it stays translatable like the other QML modules.",
        "+---",
        "+# Load the QML from the module's compiled-in resources (qrc), matching notesqml/usersq.",
        "+qmlSearch: both",
        "+",
        "+# The QML file basename (networkq.qml) inside the qrc.",
        "+qmlFilename: networkq",
        "+",
        "+# Name shown in the installer sidebar / progress tree.",
        "+qmlLabel:",
        "+    network: \"Network\"",
        "--- /dev/null",
        "+++ b/src/modules/networkq/CMakeLists.txt",
        "@@ -0,0 +1,21 @@",
        "+# === This file is part of Calamares - <https://calamares.io> ===",
        "+#",
        "+#   SPDX-License-Identifier: BSD-2-Clause",
        "+#",
        "+# Az'arch: \"Network\" QML view module (static IPv4 vs DHCP). Auto-discovered by the",
        "+# src/modules glob, so no top-level CMake edit is needed.",
        "+if(NOT WITH_QML)",
        "+    calamares_skip_module( \"networkq (QML is not supported in this build)\" )",
        "+    return()",
        "+endif()",
        "+",
        "+calamares_add_plugin(networkq",
        "+    TYPE viewmodule",
        "+    EXPORT_MACRO PLUGINDLLEXPORT_PRO",
        "+    SOURCES",
        "+        NetworkQmlViewStep.cpp",
        "+        Config.cpp",
        "+    RESOURCES",
        "+        networkq.qrc",
        "+    SHARED_LIB",
        "+)"
    ]
    # Trailing newline so the last line is terminated (patch/POSIX text file).
    return "\n".join(lines) + "\n"
