"""Az'arch calamares PACKAGE RECIPE -- the calamares part of packages.pkgbuild.

Calamares is built from OUR own recipe (never the AUR): a moderate C++/CMake build
of the pinned-sha256 Codeberg tarball, patched with three Az'arch source patches
before the build. This module owns the pinned facts and the PKGBUILD text; each of
the three source patches is large, so it lives in its OWN focused module and is
re-exported here. pkgbuild.py in turn re-exports every name below, so callers and
tests keep using `pkgbuild.calamares_defaults_patch()`, `pkgbuild.CALAMARES_VERSION`,
`pkgbuild.pkgbuild_calamares()`, etc. unchanged; and pkgbuild.recipe_dirs() (which
stays in pkgbuild.py) still assembles the calamares recipe dir from these builders.

This module is self-contained: pkgbuild_calamares() references only the pinned
constants here and the three patch-name constants re-exported below, so there is no
import back into pkgbuild.py (which would be circular).

The three patches (each in its own module, all applied in the recipe's prepare(), all
VERIFIED against the pinned calamares-3.4.2 tarball):
  calamares_patch_defaults        installer UI defaults + the Users-page refactor
  calamares_patch_region_keyboard region-driven English+region two-layout keyboard
  calamares_patch_finish_buttons  hide Back/Next on the Finish page
"""

from __future__ import annotations

# The three Az'arch source patches, each authored in its own module (they are large
# unified diffs). Re-exported so this module -- and, through it, pkgbuild.py -- exposes
# the patch builders and their filename constants as before.
from calamares_patch_defaults import (  # noqa: F401  (re-exported)
    CALAMARES_DEFAULTS_PATCH_NAME,
    calamares_defaults_patch,
)
from calamares_patch_region_keyboard import (  # noqa: F401  (re-exported)
    CALAMARES_REGION_KEYBOARD_PATCH_NAME,
    calamares_region_keyboard_patch,
)
from calamares_patch_finish_buttons import (  # noqa: F401  (re-exported)
    CALAMARES_FINISH_BUTTONS_PATCH_NAME,
    calamares_finish_buttons_patch,
)

# ---------------------------------------------------------------------------
# Pinned upstream facts (single source of truth)
# ---------------------------------------------------------------------------
CALAMARES_VERSION = "3.4.2"
# sha256 of the official release tarball, obtained by download + sha256sum.
CALAMARES_SHA256 = "733bbbb00dc9f84874bd5c22960952f317ea2537565431179fa2152b2fbfdccc"


# ---------------------------------------------------------------------------
# calamares -- built from source, always
# ---------------------------------------------------------------------------
def pkgbuild_calamares() -> str:
    return f"""\
# Maintainer: Az'arch <https://github.com/michaelilgiaev/azarch>
#
# =============================================================================
# Az'arch OWN PKGBUILD -- calamares  (generated by packages.pkgbuild)
# =============================================================================
# NOT a community/AUR recipe. Written + maintained by the Az'arch project so the
# build has no dependency on third-party packaging.
#
# Calamares is the distribution-independent graphical system installer. Az'arch
# uses it as the live-ISO installer (Manjaro-style), configured for a Btrfs
# default and optional full-disk LUKS encryption via module configs shipped on
# the ISO (this recipe only builds the binary).
#
# SOURCE (fully auditable):
#   Project : https://codeberg.org/Calamares/calamares
#   Release : https://codeberg.org/Calamares/calamares/releases/tag/v{CALAMARES_VERSION}
#   Tarball : https://codeberg.org/Calamares/calamares/releases/download/v{CALAMARES_VERSION}/calamares-{CALAMARES_VERSION}.tar.gz
#   License : GPL-3.0-or-later
#
# INTEGRITY: pinned sha256 below (from download + sha256sum). Upstream ships no
# detached .sig for the release archive, so the sha256 is the anchor; makepkg
# aborts the build on mismatch.
#
# FROM SOURCE IN EVERY TIER: a moderate C++/CMake build (minutes). Arch dropped
# calamares from extra/ (it is now AUR-only), so there is no Arch-signed binary
# to install anymore; recipe_dirs() emits this recipe for both the default and
# the --full-compile tier.
# =============================================================================

pkgname=calamares
pkgver={CALAMARES_VERSION}
pkgrel=1
pkgdesc="Distribution-independent installer framework (Az'arch build)"
arch=('x86_64')
url="https://codeberg.org/Calamares/calamares"
license=('GPL-3.0-or-later')

# Deps per upstream CMakeLists.txt for the 3.4.x line: Qt6 >= 6.5, KF6 >= 6.5,
# ECM 6.5, CMake >= 3.16, yaml-cpp, kpmcore (partitioning), polkit-qt6, boost +
# bundled pybind11 (Python job modules), squashfs-tools/rsync (unpackfs), plus
# the filesystem tools the partition module drives.
depends=(
  'qt6-base' 'qt6-svg' 'qt6-declarative'
  'kcoreaddons' 'kconfig' 'ki18n' 'kcrash'
  'kpmcore' 'yaml-cpp' 'polkit-qt6' 'boost-libs'
  'python' 'squashfs-tools' 'rsync'
  'cryptsetup' 'dosfstools' 'e2fsprogs' 'btrfs-progs' 'gptfdisk'
  'hwinfo' 'icu'
)
makedepends=('cmake' 'extra-cmake-modules' 'qt6-tools' 'boost' 'git')
optdepends=(
  'btrfs-progs: Btrfs filesystem support'
  'cryptsetup: full-disk LUKS encryption support'
  'grub: GRUB bootloader install'
)

source=(
  "calamares-${{pkgver}}.tar.gz::${{url}}/releases/download/v${{pkgver}}/calamares-${{pkgver}}.tar.gz"
  '{CALAMARES_DEFAULTS_PATCH_NAME}'
  '{CALAMARES_REGION_KEYBOARD_PATCH_NAME}'
  '{CALAMARES_FINISH_BUTTONS_PATCH_NAME}'
)
# Tarball: pinned sha256 (makepkg aborts on mismatch). Patches: shipped in-repo,
# reviewed in packages.pkgbuild (SKIP -- local files, not downloaded).
sha256sums=('{CALAMARES_SHA256}' 'SKIP' 'SKIP' 'SKIP')

prepare() {{
  cd "calamares-${{pkgver}}"
  # Az'arch installer UI defaults that Calamares only exposes in C++ (Alt+Shift
  # keyboard switch default + fixed non-reactive hostname). -p1 from the source
  # root; the pinned tarball guarantees the context matches, so a failure here
  # (e.g. after a version bump) aborts the build loudly instead of silently
  # dropping the customization.
  patch -p1 < "$srcdir/{CALAMARES_DEFAULTS_PATCH_NAME}"
  # Az'arch region-driven keyboard: when a region is picked on the Location page,
  # add the region's native layout as a switchable second (English stays first,
  # Alt+Shift), live in the installer and persisted to the target. Touches the
  # keyboard + locale modules (disjoint from the defaults patch above, so order is
  # not load-bearing). Same fail-loud-on-drift contract.
  patch -p1 < "$srcdir/{CALAMARES_REGION_KEYBOARD_PATCH_NAME}"
  # Az'arch: hide the Back + Next buttons on the Finish page (libcalamaresui
  # ViewManager). Independent of the two patches above (touches only ViewManager.cpp),
  # so order is not load-bearing. Same fail-loud-on-drift contract.
  patch -p1 < "$srcdir/{CALAMARES_FINISH_BUTTONS_PATCH_NAME}"
}}

build() {{
  cd "calamares-${{pkgver}}"
  # Qt6 + KF6, bundled pybind11 for Python job modules, QML on for the branding
  # slideshow, crash reporter off (extra deps, pointless on a live ISO).
  #
  # PIN Python to the SYSTEM interpreter (/usr/bin/python3) and its matching library.
  # calamares links libpython into libcalamares.so for the Python job modules, so the
  # linked ABI MUST match the python package the ISO ships (the `python` depends), i.e.
  # the running system's /usr/lib/libpython3.X.so. Without pinning, CMake can discover
  # an UNRELATED interpreter that happens to be on the build host (e.g. a uv-managed
  # cpython-3.12 under ~/.local/share/uv, reachable via the ~/.local/bin/python3.12
  # shim on PATH), link against THAT libpython3.12.so.1.0, and produce a calamares that
  # dies on the target with "error while loading shared libraries:
  # libpython3.12.so.1.0: cannot open shared object file" -- because the target only
  # has 3.14.
  #
  # IMPORTANT: calamares-3.4.2's CMakeLists.txt uses the LEGACY module --
  #   find_package(Python ... COMPONENTS Interpreter Development)  (no "3") --
  # and it is the Development component of THAT module which links libpython into
  # libcalamares.so. The legacy FindPython reads the Python_* hint variables; the
  # Python3_* hints only steer the newer FindPython3 (used by bundled pybind11). So we
  # MUST pin BOTH module families or FindPython silently re-discovers the uv 3.12.
  # FIND_STRATEGY=LOCATION + FIND_VIRTUALENV=STANDARD + an absolute _ROOT_DIR/_EXECUTABLE
  # make the ABI track the system python (whatever version Arch currently ships), so the
  # binary is portable to any ISO built from the same python package. Belt-and-suspenders,
  # _makepkg_one also strips ~/.local from PATH so the uv shim can't win the search.
  #
  # DISABLE libpwquality (same portability class as Python above). The users module's
  # CMakeLists does an UNCONDITIONAL find_package(LibPWQuality) with no WITH_ toggle: if
  # the BUILD host happens to have libpwquality (many distros pull it in transitively),
  # the module links libpwquality.so.1 and #defines CHECK_PWQUALITY. The Az'arch ISO does
  # NOT ship libpwquality, so that build produces a users viewmodule that fails to
  # dlopen on the target ("undefined symbol: pwquality_*" / "libpwquality.so.1: cannot
  # open shared object file") and calamares aborts with 'Module "users@users" ... FAILED'.
  # CMAKE_DISABLE_FIND_PACKAGE_LibPWQuality=ON forces that find_package to report
  # not-found, so the module builds WITHOUT the optional strong-password check -- which is
  # exactly what we want anyway (the strong-password checkbox is force-hidden and empty
  # passwords lock the account; there is no path in the Az'arch flow that uses pwquality).
  _pyexe="/usr/bin/python3"
  cmake -B build -S . \\
    -DCMAKE_BUILD_TYPE=Release \\
    -DCMAKE_INSTALL_PREFIX=/usr \\
    -DCMAKE_INSTALL_LIBDIR=lib \\
    -DPython_EXECUTABLE="$_pyexe" \\
    -DPython_ROOT_DIR=/usr \\
    -DPython_FIND_STRATEGY=LOCATION \\
    -DPython_FIND_VIRTUALENV=STANDARD \\
    -DPython3_EXECUTABLE="$_pyexe" \\
    -DPython3_ROOT_DIR=/usr \\
    -DPython3_FIND_STRATEGY=LOCATION \\
    -DPython3_FIND_VIRTUALENV=STANDARD \\
    -DCMAKE_DISABLE_FIND_PACKAGE_LibPWQuality=ON \\
    -DWITH_QT6=ON \\
    -DWITH_PYBIND11=ON \\
    -DWITH_QML=ON \\
    -DBUILD_CRASH_REPORTING=OFF \\
    -DINSTALL_POLKIT=ON \\
    -DWEBVIEW_FORCE_WEBKIT=OFF
  # -j caps parallel compile jobs. cmake's Makefiles/Ninja generator otherwise
  # auto-detects every core and pins the whole machine; AZARCH_JOBS is exported by
  # makepkg._makepkg_one (= cores - reserved), defaulting to 1 if unset.
  cmake --build build -j"${{AZARCH_JOBS:-1}}"
}}

package() {{
  cd "calamares-${{pkgver}}"
  DESTDIR="$pkgdir" cmake --install build
}}
"""
